
package view;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class RareWeaponsInfo extends javax.swing.JFrame {

    public RareWeaponsInfo() {
        initComponents();
        setTitle("Rare weapons informations");
        setSize(665, 588);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbBack = new javax.swing.JButton();
        jbF1 = new javax.swing.JButton();
        jbF2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.png"))); // NOI18N
        jbBack.setContentAreaFilled(false);
        jbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbBack);
        jbBack.setBounds(20, 500, 130, 41);

        jbF1.setContentAreaFilled(false);
        jbF1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbF1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbF1);
        jbF1.setBounds(80, 180, 160, 40);

        jbF2.setContentAreaFilled(false);
        jbF2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbF2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbF2);
        jbF2.setBounds(410, 180, 160, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/WhatsRW.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 660, 560);

        setSize(new java.awt.Dimension(676, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        MenuClasses mn = new MenuClasses();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbBackActionPerformed

    private void jbF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbF1ActionPerformed
        JOptionPane.showMessageDialog(null, "These buttons are only here to represent, keep going.");
    }//GEN-LAST:event_jbF1ActionPerformed

    private void jbF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbF2ActionPerformed
        JOptionPane.showMessageDialog(null, "These buttons are only here to represent, keep going.");
    }//GEN-LAST:event_jbF2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RareWeaponsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RareWeaponsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RareWeaponsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RareWeaponsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RareWeaponsInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbF1;
    private javax.swing.JButton jbF2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icones/info.png")));
    }
}
